// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dragging': string;
  'flowProblems': string;
  'icon': string;
  'section': string;
  'title': string;
  'toolItem': string;
  'toolPanel': string;
}
declare var cssExports: CssExports;
export = cssExports;
