// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'newFlow': string;
  'panel': string;
  'panelHead': string;
}
declare var cssExports: CssExports;
export = cssExports;
