// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block': string;
  'container': string;
  'content': string;
  'header': string;
  'hovering': string;
  'notFound': string;
  'splash': string;
}
declare var cssExports: CssExports;
export = cssExports;
