// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'copyBtn': string;
  'error': string;
  'inputWrapper': string;
  'tag': string;
  'tagInput': string;
  'wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
