// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'tag': string;
  'tagInput': string;
  'wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
