// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'description': string;
  'dropdown': string;
  'dropdownItem': string;
  'search': string;
  'singularTagBtnWrapper': string;
  'superInput': string;
  'superInputWrapper': string;
  'tag': string;
  'tagBtn': string;
  'tagBtnWrapper': string;
  'tagContentWrapper': string;
  'tagValue': string;
}
declare var cssExports: CssExports;
export = cssExports;
