// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addingItem': string;
  'btn': string;
  'dropdown': string;
  'singular': string;
  'singularTagBtnWrapper': string;
  'superInput': string;
  'superInputWrapper': string;
  'tagBtn': string;
  'tagBtnWrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
