// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'configPane': string;
  'configPopover': string;
  'dataPane': string;
  'entityEditorBody': string;
  'occurrence': string;
  'occurrenceName': string;
  'occurrencesList': string;
  'regexInputDash': string;
  'validationTag': string;
}
declare var cssExports: CssExports;
export = cssExports;
