// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contextMenuLabel': string;
  'error': string;
  'expandBtn': string;
  'fieldError': string;
  'fieldWrapper': string;
  'formHeader': string;
  'formLabel': string;
  'formSelect': string;
  'hasError': string;
  'imgWrapper': string;
  'imgWrapperActions': string;
  'input': string;
  'items': string;
  'noBorder': string;
  'noPadding': string;
  'noSelect': string;
  'searchBar': string;
  'tag': string;
  'tagInput': string;
  'textarea': string;
  'textareaWrapper': string;
  'typeField': string;
  'wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
