// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  multiSelect: string
  actionModal: string
}
declare var cssExports: CssExports
export = cssExports
