// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'column': string;
  'current': string;
  'feedbackItem': string;
  'feedbackItemsContainer': string;
  'flagged': string;
  'intentCorrectionForm': string;
  'mainContainer': string;
  'messageGroup': string;
  'profile': string;
}
declare var cssExports: CssExports;
export = cssExports;
