// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'column': string;
  'feedbackItem': string;
  'mainContainer': string;
  'profile': string;
}
declare var cssExports: CssExports;
export = cssExports;
