// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chatBubble': string;
  'conversation': string;
  'conversationDate': string;
  'conversationHeader': string;
  'conversationMessages': string;
  'conversationToggle': string;
  'current': string;
  'feedbackItem': string;
  'feedbackItemsContainer': string;
  'flagged': string;
  'fromAgent': string;
  'fromBot': string;
  'fromSystem': string;
  'intentCorrectionForm': string;
  'message': string;
  'messageAvatar': string;
  'messageContainer': string;
  'messageGroup': string;
  'noFeedbackItems': string;
  'summary': string;
}
declare var cssExports: CssExports;
export = cssExports;
