// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'textarea': string;
  'textareaWrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
