// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'controls': string;
  'editor': string;
  'editorContainer': string;
  'entity-label': string;
  'focus': string;
}
declare var cssExports: CssExports;
export = cssExports;
