// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'danger': string;
  'text': string;
  'trainCenter': string;
  'trainCenter_icon': string;
  'trainCenter_icon_wrap': string;
  'trainCenter_lang': string;
  'trainCenter_lang_code': string;
  'trainStatus': string;
  'trainStatus_message_dark': string;
  'trainStatus_message_light': string;
  'trainStatus_message_spaced': string;
  'trainStatus_pending': string;
}
declare var cssExports: CssExports;
export = cssExports;
