// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'center': string;
  'col': string;
  'graphToolTip': string;
  'left': string;
  'link': string;
  'logCritical': string;
  'logInfo': string;
  'monitoringOverview': string;
  'right': string;
  'row': string;
  'toolbar': string;
}
export const cssExports: CssExports;
export default cssExports;
