// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cancel': string;
  'content': string;
  'missingTranslation': string;
  'modal': string;
}
declare var cssExports: CssExports;
export = cssExports;
