// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'inspector': string;
  'noLineHeight': string;
  'sideForm': string;
}
declare var cssExports: CssExports;
export = cssExports;
