// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badge': string;
  'container': string;
  'deleteEntity': string;
  'entity': string;
  'header': string;
  'occurence': string;
  'occurenceDelete': string;
  'occurenceInput': string;
  'occurenceName': string;
  'removeSynonym': string;
  'selectedentity': string;
}
declare var cssExports: CssExports;
export = cssExports;
