// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'configPane': string;
  'configPopover': string;
  'dataPane': string;
  'entityEditorBody': string;
  'occurence': string;
  'occurenceName': string;
  'occurencesLabel': string;
  'regexInputDash': string;
  'validationTag': string;
}
declare var cssExports: CssExports;
export = cssExports;
