// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badge': string;
  'configPane': string;
  'configPopover': string;
  'container': string;
  'dataPane': string;
  'deleteEntity': string;
  'entity': string;
  'entityEditorBody': string;
  'header': string;
  'occurence': string;
  'occurenceName': string;
  'regexInputDash': string;
  'selectedentity': string;
}
declare var cssExports: CssExports;
export = cssExports;
