// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'last': string;
  'triggerConditionItemWrapper': string;
  'triggerConditionsWrapper': string;
  'triggerWrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
