// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'center': string;
  'left': string;
  'logCritical': string;
  'logError': string;
  'logInfo': string;
  'logWarn': string;
  'monitoringOverview': string;
  'right': string;
  'toolbar': string;
}
export const cssExports: CssExports;
export default cssExports;
