// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'color-0': string;
  'color-1': string;
  'color-2': string;
  'color-3': string;
  'color-4': string;
  'color-bg': string;
  'color-fg': string;
  'count': string;
  'editor-body': string;
  'entities-list': string;
  'hint': string;
  'index': string;
  'slot': string;
  'title': string;
  'utterance': string;
  'utterances': string;
  'wrong': string;
}
declare var cssExports: CssExports;
export = cssExports;
