// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatarPreview': string;
  'callout': string;
  'configUploadSuccess': string;
  'container': string;
  'coverPreview': string;
  'textarea': string;
}
declare var cssExports: CssExports;
export = cssExports;
