import { KeyboardShortcut, SplashScreen } from 'botpress/ui'
import React from 'react'
import { MdCode } from 'react-icons/md'

const description = `Code editor allows you to create and edit actions without leaving botpress studio. It features typings and
intelligent code completion. To edit global files and content generated by modules, you need to enable that by editing the code-editor.json configuration file.`

const rawEditorDesc = `WARNING: The raw file editor has no safeguards and you can easily mess important files. Handle with care !
You can edit any file contained in the data folder, create new files and move existing files around.`

export default ({ rawEditor }) => (
  <SplashScreen icon={<MdCode />} title={'Code Editor'} description={rawEditor ? rawEditorDesc : description}>
    <KeyboardShortcut label="Save file" keys={['ACTION', 's']} />
    <KeyboardShortcut label="New file" keys={['ACTION', 'alt', 'n']} />
    <KeyboardShortcut label="Command Palette" keys={['ACTION', 'shift', 'p']} />
  </SplashScreen>
)
