// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'divide': string;
  'tab': string;
  'tabContainer': string;
  'tabs': string;
}
declare var cssExports: CssExports;
export = cssExports;
