// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app': string;
  'escalationItem': string;
  'escalationList': string;
  'h100': string;
  'sidebar': string;
  'w100': string;
}
declare var cssExports: CssExports;
export = cssExports;
