// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'agentBtn': string;
  'agentBtnText': string;
  'agentBtnWrapper': string;
  'app': string;
  'badge': string;
  'clientName': string;
  'column': string;
  'commentForm': string;
  'conversationContainer': string;
  'conversationHistory': string;
  'coversationButton': string;
  'createdDate': string;
  'divider': string;
  'emptyContainer': string;
  'escalationItem': string;
  'escalationList': string;
  'h100': string;
  'hitlToolBar': string;
  'info': string;
  'liveConversation': string;
  'mainContent': string;
  'message': string;
  'messageList': string;
  'profileHeader': string;
  'sidebar': string;
  'sidebarContainer': string;
  'table': string;
  'unreadDot': string;
  'w100': string;
  'webchatIframe': string;
  'webchatWrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
