name: Setup
description: install dependencies and build

inputs:
  extra_filters:
    description: 'Turbo additional filters to select packages to build'
    required: false

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4 # uses the version from package.json

    - uses: actions/setup-node@v6
      with:
        node-version-file: '.tool-versions'
        package-manager-cache: false

    - name: Install Node Gyp Build
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: |
        npm install -g node-gyp-build

    - name: Install dependencies
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: pnpm i --frozen-lockfile

    - name: Build
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: pnpm build ${{ inputs.extra_filters }}
