name: Setup
description: install dependencies and build

inputs:
  filter:
    type: string
    description: 'packages to build'
    required: false
  turbo_team:
    type: string
    description: 'Turbo team'
    required: false
  turbo_token:
    type: string
    description: 'Turbo token'
    required: false

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 8.6.2
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        check-latest: true
    - name: Install dependencies
      shell: bash
      run: pnpm i --frozen-lockfile
    - name: Build
      shell: bash
      env:
        TURBO_TEAM: ${{ inputs.turbo_team }}
        TURBO_TOKEN: ${{ inputs.turbo_token }}
      run: |
        filter="${{ inputs.filter }}"
        if [ -z "$filter" ]; then
          pnpm build
        else
          pnpm build --filter $filter
        fi
