// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checklist': string;
  'docs': string;
  'header': string;
  'item': string;
  'source': string;
  'sources': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
