/**
 * A minimal, dependency-free formatter for the TypeScript typings generated by
 * llmz (typings.ts, objects.ts, hoist.ts). It supports only the small grammar
 * those generators emit — type expressions, `declare const` / `declare function`
 * declarations, `type` aliases and `export namespace` blocks — and produces
 * prettier-like output: 80 columns, 2-space indent, no semicolons in broken
 * objects, hugged single-object function params, unions wrapped with leading `|`.
 *
 * If the input cannot be tokenized or has unbalanced brackets, it is returned
 * unchanged.
 */

const WIDTH = 80
const INDENT = '  '

export type TokKind = 'word' | 'string' | 'punct' | 'block-comment' | 'line-comment'

export type Tok = {
  kind: TokKind
  text: string
  /** number of newlines in the source right before this token */
  nl: number
}

export type Group = {
  kind: 'group'
  open: string
  close: string
  children: Node[]
  nl: number
}

export type Node = Tok | Group

export const isGroup = (n: Node): n is Group => n.kind === 'group'
export const isPunct = (n: Node, text: string): boolean => !isGroup(n) && n.kind === 'punct' && n.text === text

// ---------------------------------------------------------------- tokenizer

const WORD_CHAR = /[A-Za-z0-9_$.]/

export function tokenize(src: string): Tok[] {
  const toks: Tok[] = []
  let i = 0
  let nl = 0
  const len = src.length

  while (i < len) {
    const c = src[i]!

    if (c === '\n') {
      nl++
      i++
      continue
    }

    if (c === ' ' || c === '\t' || c === '\r') {
      i++
      continue
    }

    if (c === '/' && src[i + 1] === '*') {
      const end = src.indexOf('*/', i + 2)
      if (end === -1) {
        throw new Error('unterminated block comment')
      }
      toks.push({ kind: 'block-comment', text: src.slice(i, end + 2), nl })
      nl = 0
      i = end + 2
      continue
    }

    if (c === '/' && src[i + 1] === '/') {
      let end = src.indexOf('\n', i)
      if (end === -1) {
        end = len
      }
      toks.push({ kind: 'line-comment', text: src.slice(i, end).trimEnd(), nl })
      nl = 0
      i = end
      continue
    }

    if (c === "'" || c === '"' || c === '`') {
      let j = i + 1
      while (j < len && src[j] !== c) {
        j += src[j] === '\\' ? 2 : 1
      }
      if (j >= len) {
        throw new Error('unterminated string')
      }
      toks.push({ kind: 'string', text: src.slice(i, j + 1), nl })
      nl = 0
      i = j + 1
      continue
    }

    if (c === '=' && src[i + 1] === '>') {
      toks.push({ kind: 'punct', text: '=>', nl })
      nl = 0
      i += 2
      continue
    }

    if (WORD_CHAR.test(c) || (c === '-' && /\d/.test(src[i + 1] ?? ''))) {
      let j = i + 1
      while (j < len && WORD_CHAR.test(src[j]!)) {
        j++
      }
      toks.push({ kind: 'word', text: src.slice(i, j), nl })
      nl = 0
      i = j
      continue
    }

    toks.push({ kind: 'punct', text: c, nl })
    nl = 0
    i++
  }

  return toks
}

// ------------------------------------------------------------------- parser

const CLOSER: Record<string, string> = { '{': '}', '(': ')', '[': ']', '<': '>' }

export function parse(toks: Tok[]): Node[] {
  const root: Node[] = []
  const stack: Group[] = []
  const siblings = () => (stack.length ? stack[stack.length - 1]!.children : root)

  for (const t of toks) {
    if (t.kind === 'punct' && (t.text === '{' || t.text === '(' || t.text === '[')) {
      const g: Group = { kind: 'group', open: t.text, close: CLOSER[t.text]!, children: [], nl: t.nl }
      siblings().push(g)
      stack.push(g)
      continue
    }

    if (t.kind === 'punct' && t.text === '<') {
      // '<' opens a type-argument group only right after a word (Promise<, Array<, ...)
      const prev = siblings()[siblings().length - 1]
      if (prev && !isGroup(prev) && prev.kind === 'word') {
        const g: Group = { kind: 'group', open: '<', close: '>', children: [], nl: t.nl }
        siblings().push(g)
        stack.push(g)
        continue
      }
      siblings().push(t)
      continue
    }

    if (t.kind === 'punct' && (t.text === '}' || t.text === ')' || t.text === ']' || t.text === '>')) {
      const g = stack[stack.length - 1]
      if (t.text === '>' && (!g || g.open !== '<')) {
        siblings().push(t) // stray '>' outside a type-argument group
        continue
      }
      if (!g || g.close !== t.text) {
        throw new Error('unbalanced brackets')
      }
      stack.pop()
      continue
    }

    siblings().push(t)
  }

  if (stack.length) {
    throw new Error('unbalanced brackets')
  }

  return root
}

/**
 * Cleans up generator artifacts: trailing `,`/`;` inside groups, and redundant
 * parens in value position like `[key: (string)]: ({ ... } | undefined)`.
 */
function normalize(nodes: Node[]): void {
  for (let i = 0; i < nodes.length; i++) {
    const n = nodes[i]!
    if (!isGroup(n)) {
      // unquote identifier-safe object keys: `{ "a": 1 }` -> `{ a: 1 }`
      const key = n.kind === 'string' && /^["']([A-Za-z_$][A-Za-z0-9_$]*)["']$/.exec(n.text)
      const next = nodes[i + 1]
      if (key && next && isPunct(next, ':')) {
        nodes[i] = { kind: 'word', text: key[1]!, nl: n.nl }
      }
      continue
    }

    normalize(n.children)

    while (
      n.children.length &&
      (isPunct(n.children[n.children.length - 1]!, ',') || isPunct(n.children[n.children.length - 1]!, ';'))
    ) {
      n.children.pop()
    }

    // strip parens directly after `:` when they wrap the whole value
    // (never a function type — those are followed by `=>`)
    const prev = nodes[i - 1]
    const next = nodes[i + 1]
    const wrapsWholeValue = next === undefined || isPunct(next, ';') || isPunct(next, ',')
    const isFunctionType = n.children.some((c) => isPunct(c, '=>'))
    if (n.open === '(' && n.children.length > 0 && prev && isPunct(prev, ':') && wrapsWholeValue && !isFunctionType) {
      n.children[0]!.nl = n.nl
      nodes.splice(i, 1, ...n.children)
      i--
    }
  }
}

// ----------------------------------------------------------- member splitting

function isMemberEnd(n: Node): boolean {
  if (isGroup(n)) {
    return true
  }
  return (
    n.kind === 'word' ||
    n.kind === 'string' ||
    n.kind === 'block-comment' ||
    n.kind === 'line-comment' ||
    n.text === '?'
  )
}

function isMemberStart(n: Node): boolean {
  if (isGroup(n)) {
    return false // `(` after a function name must stay glued to it
  }
  return n.kind === 'word' || n.kind === 'string' || n.kind === 'block-comment' || n.kind === 'line-comment'
}

type Members = {
  members: Node[][]
  /** true when at least one explicit `;` or `,` separator was present */
  hasSeparators: boolean
  /** true when members were separated by commas (value objects, params) */
  usedComma: boolean
}

/**
 * Splits a flat node sequence into members: on top-level `;`, on top-level `,`
 * (when enabled), after line comments, and at "safe" newlines — a newline
 * between a token that can end a member and one that can start the next one.
 * Newlines elsewhere (e.g. the generator's stray newlines around descriptions)
 * are ignored.
 */
function splitMembers(nodes: Node[], splitOnComma: boolean): Members {
  const members: Node[][] = []
  let cur: Node[] = []
  let hasSeparators = false
  let usedComma = false

  const push = () => {
    if (cur.length) {
      members.push(cur)
    }
    cur = []
  }

  for (const n of nodes) {
    if (isPunct(n, ';') || (splitOnComma && isPunct(n, ','))) {
      hasSeparators = true
      usedComma ||= (n as Tok).text === ','
      push()
      continue
    }

    const isTrailingLineComment = !isGroup(n) && n.kind === 'line-comment' && n.nl === 0

    // `...; // end of X` — a same-line comment right after a separator belongs
    // to the member that just ended
    if (isTrailingLineComment && !cur.length && members.length) {
      members[members.length - 1]!.push(n)
      continue
    }

    if (cur.length) {
      const prev = cur[cur.length - 1]!
      const prevIsLineComment = !isGroup(prev) && prev.kind === 'line-comment'
      if (prevIsLineComment || (n.nl > 0 && !isTrailingLineComment && isMemberEnd(prev) && isMemberStart(n))) {
        push()
      }
    }

    cur.push(n)
  }

  push()

  // a member made only of block comments is a leading comment of the next member
  for (let i = members.length - 2; i >= 0; i--) {
    const onlyComments = members[i]!.every((n) => !isGroup(n) && n.kind === 'block-comment')
    if (onlyComments) {
      members[i + 1]!.unshift(...members[i]!)
      members.splice(i, 1)
    }
  }

  return { members, hasSeparators, usedComma }
}

// ----------------------------------------------------------------- breaking

function hasMultilineComment(nodes: Node[]): boolean {
  return nodes.some((n) => !isGroup(n) && n.kind === 'block-comment' && n.text.includes('\n'))
}

function hasLineComment(nodes: Node[]): boolean {
  return nodes.some((n) => !isGroup(n) && n.kind === 'line-comment')
}

/** Whether a group can never be rendered on a single line. */
function mustBreak(g: Group): boolean {
  if (hasLineComment(g.children) || hasMultilineComment(g.children)) {
    return true
  }

  const { members, hasSeparators } = splitMembers(g.children, true)

  // members separated only by newlines cannot be joined back on one line
  if (members.length > 1 && !hasSeparators) {
    return true
  }

  // a member-leading comment inside {} or () forces the group open
  if ((g.open === '{' || g.open === '(') && members.some((m) => !isGroup(m[0]!) && m[0]!.kind === 'block-comment')) {
    return true
  }

  return g.children.some((c) => isGroup(c) && mustBreak(c))
}

// ------------------------------------------------------------- flat rendering

type Atom = { kind: TokKind | 'open' | 'close'; text: string }

function needSpace(a: Atom | null, b: Atom): boolean {
  if (!a) {
    return false
  }
  if (a.kind === 'open' && b.kind === 'close') {
    return false // {} () [] <>
  }
  if (b.kind === 'punct' && (b.text === ',' || b.text === ';' || b.text === ':' || b.text === '?')) {
    return false
  }
  if (b.kind === 'close') {
    return b.text === '}' // `... }` but `)`, `]`, `>` hug
  }
  if (a.kind === 'open') {
    return a.text === '{' // `{ ...` but `(`, `[`, `<` hug
  }
  if (b.kind === 'open') {
    if (b.text === '(' || b.text === '[') {
      return !(a.kind === 'word' || a.kind === 'string' || a.kind === 'close')
    }
    if (b.text === '<') {
      return false
    }
    return true // '{'
  }
  return true
}

function flatAtoms(nodes: Node[]): Atom[] {
  const out: Atom[] = []
  for (const n of nodes) {
    if (isGroup(n)) {
      out.push({ kind: 'open', text: n.open })
      out.push(...flatAtoms(n.children))
      out.push({ kind: 'close', text: n.close })
    } else {
      out.push({ kind: n.kind, text: n.text })
    }
  }
  return out
}

function joinAtoms(atoms: Atom[]): string {
  let s = ''
  let prev: Atom | null = null
  for (const a of atoms) {
    if (needSpace(prev, a)) {
      s += ' '
    }
    s += a.text
    prev = a
  }
  return s
}

const canFlatten = (nodes: Node[]): boolean =>
  !hasLineComment(nodes) && !hasMultilineComment(nodes) && !nodes.some((n) => isGroup(n) && mustBreak(n))

// ------------------------------------------------------------------ printer

class Printer {
  private _lines: string[] = []
  private _cur = ''
  private _prev: Atom | null = null

  public atom(a: Atom): void {
    if (this._prev && this._cur !== '' && needSpace(this._prev, a)) {
      this._cur += ' '
    }
    this._cur += a.text
    this._prev = a
  }

  public flat(nodes: Node[]): void {
    for (const a of flatAtoms(nodes)) {
      this.atom(a)
    }
  }

  public newline(level: number): void {
    this._lines.push(this._cur)
    this._cur = INDENT.repeat(level)
    this._prev = null
  }

  public blankLine(level: number): void {
    this._lines.push(this._cur)
    this._lines.push('')
    this._cur = INDENT.repeat(level)
    this._prev = null
  }

  public get column(): number {
    return this._cur.length
  }

  public get lineIsEmpty(): boolean {
    return this._cur.trim() === ''
  }

  public comment(text: string, level: number): void {
    const lines = text.split('\n').map((l) => l.trim())
    for (let i = 0; i < lines.length; i++) {
      if (i > 0) {
        this.newline(level)
        this._cur += lines[i]!.startsWith('*') ? ' ' : ''
        this._cur += lines[i]!
      } else {
        this.atom({ kind: 'block-comment', text: lines[i]! })
      }
      this._prev = { kind: 'block-comment', text: lines[i]! }
    }
  }

  public toString(): string {
    this._lines.push(this._cur)
    const out = this._lines
      .map((l) => (l.trim() === '' ? '' : l))
      .join('\n')
      .replace(/\n{3,}/g, '\n\n')
    this._lines.pop()
    return out.trim()
  }
}

function flatWidth(nodes: Node[]): number | null {
  if (!canFlatten(nodes)) {
    return null
  }
  return joinAtoms(flatAtoms(nodes)).length
}

function fitsFlat(p: Printer, nodes: Node[]): boolean {
  const width = flatWidth(nodes)
  return width !== null && p.column + width + 1 <= WIDTH
}

/**
 * Emits nodes left to right, breaking groups in place when they don't fit.
 * `tailWidth` is the flat width of whatever the caller will emit right after
 * these nodes on the same line (e.g. `): unknown` after hugged params).
 */
function walk(p: Printer, nodes: Node[], level: number, tailWidth = 0): void {
  for (let i = 0; i < nodes.length; i++) {
    const n = nodes[i]!
    if (isGroup(n)) {
      const own = mustBreak(n) ? null : flatWidth([n])
      // the line ends at the first line comment, so ignore it and what follows
      let restNodes = nodes.slice(i + 1)
      const lineCommentIdx = restNodes.findIndex((x) => !isGroup(x) && x.kind === 'line-comment')
      if (lineCommentIdx !== -1) {
        restNodes = restNodes.slice(0, lineCommentIdx)
      }
      const rest = flatWidth(restNodes)
      const after = rest === null ? 0 : rest + tailWidth
      if (own !== null && p.column + 1 + own + after <= WIDTH) {
        p.flat([n])
      } else {
        breakGroup(p, n, level, after)
      }
      continue
    }

    if (n.kind === 'block-comment' && n.text.includes('\n')) {
      if (!p.lineIsEmpty) {
        p.newline(level)
      }
      p.comment(n.text, level)
      p.newline(level)
      continue
    }

    if (n.kind === 'line-comment') {
      p.atom({ kind: 'line-comment', text: n.text })
      continue
    }

    p.atom({ kind: n.kind, text: n.text })
  }
}

function breakGroup(p: Printer, g: Group, level: number, tailWidth = 0): void {
  if (g.open === '<') {
    // never break the <> itself; let inner groups break
    p.atom({ kind: 'open', text: '<' })
    walk(p, g.children, level, tailWidth + 1)
    p.atom({ kind: 'close', text: '>' })
    return
  }

  const { members, usedComma } = splitMembers(g.children, true)

  const hasLeadingComment = members.some((m) => !isGroup(m[0]!) && m[0]!.kind === 'block-comment')

  // hug single-param function args ending in a plain object: `(args: {` ... `})`
  // — but not unions or comment-led params, which read better one per line
  const single = members.length === 1 ? members[0]! : null
  const endsInObject =
    !!single && isGroup(single[single.length - 1]!) && (single[single.length - 1]! as Group).open === '{'
  const hasUnion = !!single && single.some((n) => isPunct(n, '|'))
  if (g.open === '(' && endsInObject && !hasUnion && !hasLeadingComment) {
    p.atom({ kind: 'open', text: '(' })
    walk(p, g.children, level, tailWidth + 1)
    p.atom({ kind: 'close', text: ')' })
    return
  }

  const separator = g.open === '(' || g.open === '[' ? ',' : usedComma ? ',' : null
  const trailingSeparator = g.open === '(' || g.open === '['

  p.atom({ kind: 'open', text: g.open })
  for (let i = 0; i < members.length; i++) {
    p.newline(level + 1)
    renderMember(p, members[i]!, level + 1)
    if (separator && (trailingSeparator || i < members.length - 1)) {
      p.atom({ kind: 'punct', text: separator })
    }
  }
  p.newline(level)
  p.atom({ kind: 'close', text: g.close })
}

/** Renders one member (or statement body): leading comments, then flat / union-break / walk. */
function renderMember(p: Printer, nodes: Node[], level: number): void {
  let rest = nodes

  // leading block comments go on their own line(s)
  while (rest.length && !isGroup(rest[0]!) && rest[0]!.kind === 'block-comment') {
    const c = rest[0]! as Tok
    p.comment(c.text, level)
    rest = rest.slice(1)
    if (rest.length) {
      p.newline(level)
    }
  }

  if (!rest.length) {
    return
  }

  if (fitsFlat(p, rest)) {
    p.flat(rest)
    return
  }

  // union break: `key:` + one `| option` per line — only when the union is not
  // a function return type (i.e. no top-level () group before the first |)
  const pipeIdx = rest.findIndex((n) => isPunct(n, '|'))
  const parenIdx = rest.findIndex((n) => isGroup(n) && n.open === '(')
  if (pipeIdx !== -1 && (parenIdx === -1 || pipeIdx < parenIdx)) {
    let colonIdx = -1
    for (let i = 0; i < pipeIdx; i++) {
      if (isPunct(rest[i]!, ':') || isPunct(rest[i]!, '=')) {
        colonIdx = i
      }
    }
    const prefix = rest.slice(0, colonIdx + 1)
    const tail = rest.slice(colonIdx + 1)
    if (!prefix.length || fitsFlat(p, prefix)) {
      p.flat(prefix)

      const options: Node[][] = []
      let cur: Node[] = []
      for (const n of tail) {
        if (isPunct(n, '|')) {
          options.push(cur)
          cur = []
        } else {
          cur.push(n)
        }
      }
      options.push(cur)

      // without a `key:` prefix the options list starts at the current level
      const optionLevel = prefix.length ? level + 1 : level
      let first = true
      for (const option of options) {
        if (!option.length) {
          continue // leading `|` (idempotent re-format)
        }
        if (!first || prefix.length) {
          p.newline(optionLevel)
        }
        first = false
        p.atom({ kind: 'punct', text: '|' })
        walk(p, option, optionLevel + 1)
      }
      return
    }
  }

  // assignments: keep everything up to `=` flat when it fits, break the value
  const eqIdx = rest.findIndex((n) => isPunct(n, '='))
  if (eqIdx !== -1) {
    const prefix = rest.slice(0, eqIdx + 1)
    if (fitsFlat(p, prefix)) {
      p.flat(prefix)
      walk(p, rest.slice(eqIdx + 1), level)
      return
    }
  }

  walk(p, rest, level)
}

// --------------------------------------------------------------- statements

function renderStatements(p: Printer, nodes: Node[], level: number): void {
  const { members: statements } = splitMembers(nodes, false)

  for (let i = 0; i < statements.length; i++) {
    const stmt = statements[i]!
    if (i > 0) {
      if ((stmt[0]!.nl ?? 0) >= 2) {
        p.blankLine(level)
      } else {
        p.newline(level)
      }
    }
    renderStatement(p, stmt, level)
  }
}

function renderStatement(p: Printer, stmt: Node[], level: number): void {
  // leading block comments go on their own line(s)
  while (stmt.length && !isGroup(stmt[0]!) && stmt[0]!.kind === 'block-comment') {
    p.comment((stmt[0]! as Tok).text, level)
    stmt = stmt.slice(1)
    if (stmt.length) {
      p.newline(level)
    }
  }
  if (!stmt.length) {
    return
  }

  // namespace / module blocks get statement treatment inside their braces
  const nsIdx = stmt.findIndex(
    (n) => !isGroup(n) && n.kind === 'word' && (n.text === 'namespace' || n.text === 'module')
  )
  const bodyIdx = stmt.findIndex((n) => isGroup(n) && n.open === '{')
  if (nsIdx !== -1 && bodyIdx > nsIdx) {
    const body = stmt[bodyIdx]! as Group
    p.flat(stmt.slice(0, bodyIdx))
    p.atom({ kind: 'open', text: '{' })
    if (body.children.length) {
      p.newline(level + 1)
      renderStatements(p, body.children, level + 1)
      p.newline(level)
    }
    p.atom({ kind: 'close', text: '}' })
    walk(p, stmt.slice(bodyIdx + 1), level)
    return
  }

  renderMember(p, stmt, level)
}

// ------------------------------------------------------------------- public

/** Formats typings, throwing on input it cannot parse (unbalanced brackets, etc.) */
export function formatTypingsUnsafe(typings: string): string {
  const tokens = tokenize(typings)
  if (!tokens.length) {
    return ''
  }
  const nodes = parse(tokens)
  normalize(nodes)
  const printer = new Printer()
  renderStatements(printer, nodes, 0)
  return printer.toString()
}

/** Formats typings, returning the input unchanged when it cannot be parsed */
export function formatTypings(typings: string): string {
  try {
    return formatTypingsUnsafe(typings)
  } catch {
    return typings
  }
}
