// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionSelect': string;
  'callApiNote': string;
  'callApiSection': string;
  'callApiWarning': string;
  'contentPicker': string;
  'intentSelect': string;
  'keywords': string;
  'modalContent': string;
  'notFoundSelect': string;
  'slotSelect': string;
  'warning': string;
}
declare var cssExports: CssExports;
export = cssExports;
