// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionSelect': string;
  'callApiNote': string;
  'callApiTabs': string;
  'callApiTextArea': string;
  'callApiWarning': string;
  'contentPicker': string;
  'errorContainer': string;
  'intentSelect': string;
  'keywords': string;
  'modalContent': string;
  'notFoundSelect': string;
  'padded': string;
  'skillSection': string;
  'skillToolTipPopover': string;
  'slotSelect': string;
  'tipLabel': string;
  'warning': string;
}
declare var cssExports: CssExports;
export = cssExports;
