// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'divider': string;
  'emptyState': string;
  'group': string;
  'label': string;
  'variables': string;
  'wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
