FROM ubuntu:20.04 as build

RUN apt-get update && apt-get -y install curl git dirmngr apt-transport-https lsb-release ca-certificates bash unzip
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get -y install nodejs gcc g++ make 
RUN npm install --global yarn typescript ts-node

WORKDIR /app
COPY . /app
RUN cd packages/runtime && yarn && yarn build && yarn package

RUN mkdir outputs && \
  unzip /app/packages/runtime/archives/runtime-v*-linux-x64.zip -d outputs 

FROM ubuntu:20.04

WORKDIR /botpress

RUN apt-get update && apt-get install -y wget ca-certificates && \
  update-ca-certificates && \
  chgrp -R 0 /botpress && \
	chmod -R g=u /botpress && \
	apt-get install -y tzdata && \
  ln -fs /usr/share/zoneinfo/UTC /etc/localtime && \
  dpkg-reconfigure --frontend noninteractive tzdata

COPY --from=build /app/outputs /botpress

ENV BP_IS_DOCKER=true
ENV LANG=C.UTF-8

EXPOSE 3000

ENTRYPOINT ["/botpress/runtime"]
