packages:
  - packages/*
  - packages/cli/templates/*
  - integrations/*
  - interfaces/*
  - bots/*
  - plugins/*

minimumReleaseAge: 10080 # 7 days

minimumReleaseAgeExclude:
  - '@bpinternal/*'
  - '@botpress/*'
