saveWorkspaceProtocol: false
linkWorkspacePackages: true
preferWorkspacePackages: true
packages:
  - packages/*
  - packages/cli/templates/*
  - integrations/*
  - interfaces/*
  - bots/*
  - plugins/*
