packages:
  - packages/*
  - packages/cli/templates/*
  - integrations/*
  - interfaces/*
  - bots/*
  - plugins/*

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@botpress/*'
  - '@bpinternal/*'
