// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'main': string;
  'mainLayout': string;
  'mainSplitPaneWToolbar': string;
  'unlicensed': string;
}
export const cssExports: CssExports;
export default cssExports;
