// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'item': string;
  'section-next': string;
}
declare var cssExports: CssExports;
export = cssExports;
