// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'collapse': string;
  'formGroup': string;
  'group': string;
  'header': string;
  'icon': string;
  'isCheckbox': string;
  'labelBtn': string;
  'moreInfo': string;
  'noSection': string;
  'requiredField': string;
}
declare var cssExports: CssExports;
export = cssExports;
