// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'addFilters': string;
  'card': string;
  'dot': string;
  'emptyMessage': string;
  'error': string;
  'filters': string;
  'formTime': string;
  'formUserTimezone': string;
  'mainPanel': string;
  'modal': string;
  'navbar': string;
  'newButton': string;
  'progress': string;
  'scheduledDate': string;
  'scheduledTable': string;
  'smallButton': string;
  'table': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
