// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dot': string;
  'emptyMessage': string;
  'mainPanel': string;
  'navbar': string;
  'progress': string;
  'scheduledDate': string;
  'scheduledTable': string;
  'smallButton': string;
}
declare var cssExports: CssExports;
export = cssExports;
