// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'description': string;
  'editor': string;
  'focused': string;
  'insertBtn': string;
  'mention': string;
  'mentionSuggestions': string;
  'mentionSuggestionsEntry': string;
  'mentionSuggestionsEntryFocused': string;
  'mentionSuggestionsEntryText': string;
  'properties': string;
  'suggestion-type': string;
  'variable': string;
  'variables': string;
}
declare var cssExports: CssExports;
export = cssExports;
