// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addBtn': string;
  'deleteImg': string;
  'fieldError': string;
  'fieldWrapper': string;
  'formSelect': string;
  'groupLabel': string;
  'imgWrapper': string;
  'imgWrapperActions': string;
  'input': string;
  'label': string;
  'labelWrapper': string;
  'textarea': string;
}
declare var cssExports: CssExports;
export = cssExports;
