// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'header': string;
  'in': string;
  'nodeWrapper': string;
  'out': string;
  'outRouting': string;
  'ports': string;
}
declare var cssExports: CssExports;
export = cssExports;
