// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'rightSidebar': string;
  'show': string;
  'wRightSidebar': string;
}
declare var cssExports: CssExports;
export = cssExports;
