// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'boxed': string;
  'container': string;
  'divide': string;
  'flex': string;
  'fullWidth': string;
  'hidden': string;
  'padded': string;
  'small': string;
  'tab': string;
  'tabContainer': string;
  'tabs': string;
  'verticalTab': string;
}
export const cssExports: CssExports;
export default cssExports;
