// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contentImgWrapper': string;
  'img': string;
  'secondaryText': string;
  'text': string;
  'textWrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
