// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'f1Container': string;
  'f1Section': string;
  'inline': string;
  'main': string;
  'results': string;
  'span': string;
  'toolbar': string;
  'verticalText': string;
  'working': string;
}
declare var cssExports: CssExports;
export = cssExports;
