// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'f1Container': string;
  'f1Section': string;
  'toolbar': string;
  'working': string;
}
declare var cssExports: CssExports;
export = cssExports;
