// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'conversations': string;
  'datepicker': string;
  'daypicker-item': string;
  'fetch-more': string;
  'message-elements': string;
  'message-group': string;
  'message-group-confidence': string;
  'message-group-decision': string;
  'message-group-explanation': string;
  'message-group-flag': string;
  'message-group-header': string;
  'message-header': string;
  'message-header-icon_item': string;
  'message-header-icons': string;
  'message-incomming': string;
  'message-inspect': string;
  'message-inspector': string;
  'message-inspector-hidden': string;
  'message-lastdate': string;
  'message-list': string;
  'message-list-full': string;
  'message-list-partial': string;
  'message-outgoing': string;
  'message-sender': string;
  'message-title': string;
  'message-viewer': string;
  'messageTaskBar': string;
  'messageTaskBarFilter': string;
  'messageTaskBarFlagIcon': string;
  'messageTaskBarUnflagIcon': string;
  'noConvIcon': string;
  'quit-inspector': string;
}
declare var cssExports: CssExports;
export = cssExports;
