// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'conversations': string;
  'conversations-count': string;
  'conversations-entry': string;
  'conversations-filter': string;
  'conversations-icons': string;
  'conversations-refresh': string;
  'conversations-sessionId': string;
  'conversations-text': string;
  'conversations-titlebar': string;
  'daypicker-item': string;
  'fetch-more': string;
  'history-component': string;
  'message-elements': string;
  'message-group': string;
  'message-group-confidence': string;
  'message-group-decision': string;
  'message-group-explanation': string;
  'message-group-header': string;
  'message-header': string;
  'message-header-icon_item': string;
  'message-header-icons': string;
  'message-incomming': string;
  'message-inspect': string;
  'message-inspector': string;
  'message-inspector-hidden': string;
  'message-lastdate': string;
  'message-list': string;
  'message-list-full': string;
  'message-list-partial': string;
  'message-outgoing': string;
  'message-sender': string;
  'message-title': string;
  'message-viewer': string;
  'no-conv': string;
  'query-options': string;
  'query-options-daypick': string;
  'query-options-from_to': string;
  'quit-inspector': string;
}
declare var cssExports: CssExports;
export = cssExports;
