// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'botReplies': string;
  'conversations': string;
  'datepicker': string;
  'fetch-more': string;
  'filtersCheckbox': string;
  'iconWrap': string;
  'inspector': string;
  'interaction': string;
  'interactionStatus': string;
  'message-viewer': string;
  'messageGroup': string;
  'noConvIcon': string;
  'taskBarText': string;
  'userMessage': string;
}
declare var cssExports: CssExports;
export = cssExports;
