import keyMirror from 'keymirror'

export default keyMirror({
  MODULES_RECEIVED: null,
  ALL_NOTIFICATIONS_RECEIVED: null,
  NEW_NOTIFICATIONS_RECEIVED: null,
  TOGGLE_LICENSE_MODAL: null,
  BOT_INFORMATION_RECEIVED: null,
  LICENSE_RECEIVED: null,
  LICENSE_CHANGED: null,
  VIEW_MODE_CHANGED: null,
  TOGGLE_ABOUT_MODAL: null,
  USER_RECEIVED: null,
  RULES_RECEIVED: null,
  UPDATE_GLOBAL_STYLE: null
})
