// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'moduleItem': string;
  'moduleItemSwitch': string;
}
export const cssExports: CssExports;
export default cssExports;
