// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'autotrainToggle': string;
  'trainingControl': string;
}
declare var cssExports: CssExports;
export = cssExports;
