// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionDialogContent': string;
  'actionSelectItem': string;
  'actionServer': string;
  'addContentBtn': string;
  'advancedSettingsBtn': string;
  'alignBtnRight': string;
  'category': string;
  'checkboxLabel': string;
  'contentTypeField': string;
  'deleteBtn': string;
  'description': string;
  'emptyState': string;
  'fieldError': string;
  'fieldWrapper': string;
  'formHeader': string;
  'formLabel': string;
  'formSelect': string;
  'imgWrapper': string;
  'imgWrapperActions': string;
  'innerWrapper': string;
  'insertBtn': string;
  'items': string;
  'multipleInputs': string;
  'textInput': string;
  'textarea': string;
  'textareaWrapper': string;
  'wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
