// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionModal': string;
  'editorWrap': string;
  'hidden': string;
}
declare var cssExports: CssExports;
export = cssExports;
