@api = http://localhost:3200

### get info
# @name info
GET {{api}}/info


### do a training
# @name train
POST {{api}}/train
Content-Type: application/json

{
  "language": "en",
  "intents": [
    {
      "name": "fruit-is-moldy",
      "contexts": ["grocery"],
      "utterances": [
        "fruit is moldy",
        "this fruit is moldy",
        "this [banana](fruit) is not good to eat",
        "theses [oranges](fruit) have passed",
        "theses [grapes](fruit) look bad",
        "theses [apples](fruit) look soo moldy"
      ],
      "slots": [
        {
          "name": "moldy_fruit",
          "entities": ["fruits"]
        }
      ]
    },
    {
      "name": "hello",
      "contexts": ["global", "grocery"],
      "slots": [],
      "utterances": [
        "good day!",
        "good morning",
        "holla",
        "bonjour",
        "hey there",
        "hi bot",
        "hey bot",
        "hey robot",
        "hey!",
        "hi",
        "hello"
      ]
    },
    {
      "name": "talk-to-manager",
      "contexts": ["grocery"],
      "utterances": [
        "talk to manager",
        "I want to talk to the manager",
        "Who's your boss?",
        "Can talk to the person in charge?",
        "I'd like to speak to your manager",
        "Can I talk to your boss? plz",
        "I wanna speak to manager please",
        "let me speak to your boss or someone"
      ],
      "slots": []
    },
    {
      "name": "where-is",
      "contexts": ["grocery"],
      "utterances": [
        "where is [milk](thing_to_search) ?",
        "where are [apples](thing_to_search) ?",
        "can you help me find [apples](thing_to_search) ?",
        "I'm searching for [pie](thing_to_search) ?",
        "where is the [milk](thing_to_search) ?",
        "where are the [milk](thing_to_search) ?"
      ],
      "slots": [
        {
          "name": "thing_to_search",
          "entities": ["fruits", "any"]
        }
      ]
    }
  ],
  "contexts": ["grocery", "global"],
  "entities": [
    {
      "name": "fruits",
      "type": "list",
      "fuzzy": 0.9,
      "values": [
        { "name": "banana", "synonyms": ["bananas"] },
        { "name": "apple", "synonyms": ["apples"] },
        { "name": "grape", "synonyms": ["grapes"] },
        { "name": "orange", "synonyms": ["oranges"] }
      ]
    }
  ],
  "seed": 42,
  "appSecret": "123456",
  "appId": "some-application-id"
}
###
@modelId = {{train.response.body.modelId}}



### get training-status
# @name train-status
GET {{api}}/train/{{modelId}}?appSecret=123456&appId=some-application-id


### cancel training
# @name cancel-training
POST {{api}}/train/{{modelId}}/cancel
Content-Type: application/json

{
  "appSecret": "123456",
  "appId": "some-application-id"
}

### predict for sentence
# @name predict
POST {{api}}/predict/{{modelId}}
Content-Type: application/json

{
  "utterances" : [
    "These grapes look moldy",
    "Can I talk with the person in charge?",
    "My flight is at 9 pm"
  ],
  "appSecret": "123456",
  "appId": "some-application-id"
}

### detect language for sentences
# @name detectlang
POST {{api}}/detect-lang
Content-Type: application/json

{
  "utterances" : [
    "These grapes look moldy",
    "Est-ce que je peux parler à votre patron?",
    "mi vuelo es a las 9pm"
  ],
  "appSecret": "123456",
  "appId": "some-application-id"
}

### list models
# @name list-models
GET {{api}}/models?appSecret=123456&appId=some-application-id

### list models
# @name prune-models
POST {{api}}/models/prune
Content-Type: application/json

{
  "appSecret": "123456",
  "appId": "some-application-id"
}