// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addBtn': string;
  'collapsibleWrapper': string;
  'content': string;
  'empty': string;
  'headerWrapper': string;
  'items': string;
  'left': string;
  'questionHeader': string;
  'questionWrapper': string;
  'right': string;
  'tag': string;
  'textarea': string;
}
declare var cssExports: CssExports;
export = cssExports;
