// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addBtn': string;
  'collapsibleWrapper': string;
  'content': string;
  'contentAnswer': string;
  'empty': string;
  'errorIcon': string;
  'expanded': string;
  'hasError': string;
  'header': string;
  'headerWrapper': string;
  'incomplete': string;
  'items': string;
  'left': string;
  'questionHeader': string;
  'questionWrapper': string;
  'right': string;
  'tag': string;
  'textarea': string;
  'textareaWrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
