// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'botName': string;
  'flag': string;
  'flagWrapper': string;
  'item': string;
  'langItem': string;
  'langSwitherMenu': string;
  'menu': string;
  'statusBar': string;
}
export const cssExports: CssExports;
export default cssExports;
