// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'amendForm': string;
  'amendFormPicker': string;
  'card': string;
  'chatPreview': string;
  'chatPreviewAvatar': string;
  'chatPreviewMessage': string;
  'chatPreviewMessage_Current': string;
  'chatPreviewMessage_Incoming': string;
  'chatPreviewMessage_Outgoing': string;
  'chatPreviewText': string;
  'newEventPreview': string;
  'popover': string;
  'selectedCard': string;
}
declare var cssExports: CssExports;
export = cssExports;
