// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'aside': string;
  'aside-tabs': string;
  'aside__logo': string;
  'block': string;
  'block-header': string;
  'block-main': string;
  'container': string;
  'main': string;
  'main-content': string;
  'sidebar': string;
  'sidebar-tabs': string;
}
declare var cssExports: CssExports;
export = cssExports;
