// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bar-btn': string;
  'dropdown': string;
  'empty': string;
  'header': string;
  'item': string;
  'item-unread': string;
  'level-error': string;
  'level-info': string;
  'level-success': string;
  'mark-read-btn': string;
  'markAsReadButton': string;
  'message': string;
  'topMenu': string;
}
declare var cssExports: CssExports;
export = cssExports;
