// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'card_body': string;
  'card_text': string;
  'card_title': string;
  'centered_container': string;
  'homepage': string;
  'inner': string;
  'login_box': string;
  'login_btn': string;
  'logo': string;
  'middle': string;
}
export const cssExports: CssExports;
export default cssExports;
