// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'formGroup': string;
  'isCheckbox': string;
  'labelBtn': string;
  'moreInfo': string;
  'requiredField': string;
}
declare var cssExports: CssExports;
export = cssExports;
