// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'inline': string;
  'main': string;
  'verticalText': string;
}
declare var cssExports: CssExports;
export = cssExports;
