// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'info': string;
  'info_container': string;
  'info_icon': string;
  'info_text': string;
}
declare var cssExports: CssExports;
export = cssExports;
