// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'flag': string;
  'language': string;
  'languages_grid': string;
  'languages_list': string;
}
export const cssExports: CssExports;
export default cssExports;
