// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chooseContainer': string;
  'container': string;
  'deleteEntity': string;
  'emtpyStateIcon': string;
  'headerToolbar': string;
  'synonym': string;
}
declare var cssExports: CssExports;
export = cssExports;
