// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'admin': string;
  'category': string;
  'categoryWrapper': string;
  'command': string;
  'external': string;
  'headerWrapper': string;
  'item': string;
  'kbd': string;
  'module': string;
  'shortcut': string;
  'studio': string;
}
declare var cssExports: CssExports;
export = cssExports;
