// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'warning': string;
  'warning_icon': string;
  'warning_text': string;
}
declare var cssExports: CssExports;
export = cssExports;
