// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'date': string;
  'imgContainer': string;
  'textPrefix': string;
  'user': string;
}
declare var cssExports: CssExports;
export = cssExports;
