// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hideDismiss': string;
  'toaster': string;
}
declare var cssExports: CssExports;
export = cssExports;
