blank_issues_enabled: false
contact_links:
  - name: Botpress V12
    url: https://github.com/botpress/v12
    about: If you're experiencing issues when using the on premise version of Botpress, please report the issue on the v12 repo.
  - name: Botpress Cloud
    url: https://discord.gg/botpress
    about: To get assistance as fast as possible, please reach us on our Discord server.
