// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'gray': string;
  'green': string;
  'red': string;
  'yellow': string;
}
declare var cssExports: CssExports;
export = cssExports;
