name: Deploy Integrations
description: Deploys integrations

input:
  environment:
    type: choice
    description: 'Environment to deploy to'
    required: true
    options:
      - staging
      - production
  force:
    type: boolean
    description: 'Force re-deploying integrations'
    required: false
  sentry_auth_token:
    description: 'Sentry auth token'
    required: true
  token_cloud_ops_account:
    description: 'Cloud Ops account token'
    required: true
  cloud_ops_workspace_id:
    description: 'Cloud Ops workspace id'
    required: true
  gmail_client_id:
    description: 'Gmail client id'
    required: true
  gmail_client_secret:
    description: 'Gmail client secret'
    required: true
  gmail_topic_name:
    description: 'Gmail topic name'
    required: true
  linear_client_id:
    description: 'Linear client id'
    required: true
  linear_client_secret:
    description: 'Linear client secret'
    required: true
  linear_webhook_signing_secret:
    description: 'Linear webhook signing secret'
    required: true
  slack_client_id:
    description: 'Slack client id'
    required: true
  slack_client_secret:
    description: 'Slack client secret'
    required: true

runs:
  using: 'composite'
  steps:
    - name: List Sentry Integrations
      id: list_sentry_integrations
      shell: bash
      run: |
        script_path="./.github/scripts/ls-sentry-integrations.sh"
        chmod +x $script_path
        filter=$($script_path)
        echo "::set-output name=filter::$filter"
    - name: Inject SourceMaps
      shell: bash
      run: pnpm -r --stream ${{ steps.list_sentry_integrations.outputs.filter }} exec sentry-cli sourcemaps inject .botpress/dist
    - name: Upload SourceMaps
      shell: bash
      run: pnpm -r --stream ${{ steps.list_sentry_integrations.outputs.filter }} exec sentry-cli sourcemaps upload --release=${{ github.sha }} --url-prefix '~' .botpress/dist
      env:
        SENTRY_AUTH_TOKEN: ${{ inputs.sentry_auth_token }}
        SENTRY_ORG: botpress-rm
        SENTRY_RELEASE: ${{ github.sha }}
    - name: Deploys Integrations
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        TOKEN_CLOUD_OPS_ACCOUNT: ${{ inputs.token_cloud_ops_account }}
        CLOUD_OPS_WORKSPACE_ID: ${{ inputs.cloud_ops_workspace_id }}
        SENTRY_RELEASE: ${{ github.sha }}
        SENTRY_ENVIRONMENT: ${{ inputs.environment }}
      shell: bash
      run: |
        api_url="${{ inputs.environment == 'staging' && 'https://api.botpress.dev' || 'https://api.botpress.cloud' }}"

        # login

        echo "### Logging in to $api_url ###"
        pnpm bp login -y --api-url $api_url --workspaceId "$CLOUD_OPS_WORKSPACE_ID" --token "$TOKEN_CLOUD_OPS_ACCOUNT"

        # deploy

        integration_paths=$(pnpm list -F "@botpresshub/*" -F "!asana" -F "!trello" -F "!webchat" --json | jq -r "map(".path") | .[]")

        for integration_path in $integration_paths; do
            integration=$(basename $integration_path)
            exists=$(./.github/scripts/integration-exists.sh $integration)

            base_command="bp deploy -v -y --noBuild --public --allowDeprecated"
            if [ $integration == "gmail" ]; then
                base_command="$base_command --secrets CLIENT_ID=${{ inputs.gmail_client_id }} --secrets CLIENT_SECRET=${{ inputs.gmail_client_secret }} --secrets TOPIC_NAME=${{ inputs.gmail_topic_name }}"
            elif [ $integration == "linear" ]; then
                base_command="$base_command --secrets CLIENT_ID=${{ inputs.linear_client_id }} --secrets CLIENT_SECRET=${{ inputs.linear_client_secret }} --secrets WEBHOOK_SIGNING_SECRET=${{ inputs.linear_webhook_signing_secret }}"
            elif [ $integration == "slack" ]; then
                base_command="$base_command --secrets CLIENT_ID=${{ inputs.slack_client_id }} --secrets CLIENT_SECRET=${{ inputs.slack_client_secret }} --secrets SIGNING_SECRET=${{ inputs.slack_signing_secret }}"
            fi
            
            redeploy=${{ inputs.force && 1 || 0 }}
            if [ $exists -eq 0 ]; then
                echo -e "\nDeploying integration: ### $integration ###\n"
                pnpm retry -n 2 -- pnpm -F $integration -c exec -- "$base_command"
            elif [ $redeploy -eq 1 ]; then
                echo -e "\nRe-deploying integration: ### $integration ###\n"
                pnpm retry -n 2 -- pnpm -F $integration -c exec -- "$base_command"
            else
                echo -e "\nSkipping integration: ### $integration ###\n"
            fi
        done
