// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'label': string;
  'left': string;
  'legend': string;
  'right': string;
  'root': string;
  'selected': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
