// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'toolItem': string;
  'toolbar': string;
}
declare var cssExports: CssExports;
export = cssExports;
