// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'metricsContainer': string;
  'numberMetric': string;
  'numberMetricName': string;
  'numberMetricValue': string;
}
declare var cssExports: CssExports;
export = cssExports;
