// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alignedLeft': string;
  'appliedFilters': string;
  'chartMetric': string;
  'empty': string;
  'emptyState': string;
  'filterItem': string;
  'filters': string;
  'filtersShowing': string;
  'fullGrid': string;
  'fullWidth': string;
  'genericMetric': string;
  'half': string;
  'header': string;
  'inline': string;
  'innerWrapper': string;
  'list': string;
  'mainWrapper': string;
  'metricName': string;
  'metricWrapper': string;
  'metricsContainer': string;
  'multiple': string;
  'numberMetricValue': string;
  'pageTitle': string;
  'progressMetric': string;
  'progressMetricLabel': string;
  'quarter': string;
  'radialChart': string;
  'radialChartLabel': string;
  'section': string;
  'sectionsWrapper': string;
  'threeQuarterGrid': string;
  'wIcon': string;
}
declare var cssExports: CssExports;
export = cssExports;
