// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'centered': string;
  'diagramContainer': string;
  'diagramHidden': string;
  'emptyState': string;
  'floatingInfo': string;
  'hidden': string;
  'insertMode': string;
  'insertNode': string;
}
declare var cssExports: CssExports;
export = cssExports;
