// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'floatingInfo': string;
  'insertMode': string;
  'insertNode': string;
}
declare var cssExports: CssExports;
export = cssExports;
