// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionBtn': string;
  'createItem': string;
  'editButton': string;
}
declare var cssExports: CssExports;
export = cssExports;
