// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'divide': string;
  'end': string;
  'entry': string;
  'level': string;
  'level-debug': string;
  'level-error': string;
  'level-info': string;
  'level-silly': string;
  'level-verbose': string;
  'level-warn': string;
  'logs': string;
  'message': string;
  'tab': string;
  'tabs': string;
  'time': string;
}
declare var cssExports: CssExports;
export = cssExports;
