// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'brain': string;
  'clickable': string;
  'color-1': string;
  'color-10': string;
  'color-2': string;
  'color-3': string;
  'color-4': string;
  'color-5': string;
  'color-6': string;
  'color-7': string;
  'color-8': string;
  'color-9': string;
  'flash': string;
  'item': string;
  'langItem': string;
  'langSwitherMenu': string;
  'list': string;
  'nluUnhealthy': string;
  'right': string;
  'scoreLine': string;
  'shortcut': string;
  'statusBar': string;
  'switchBotMenu': string;
  'worker': string;
}
declare var cssExports: CssExports;
export = cssExports;
