// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'clickable': string;
  'flash': string;
  'item': string;
  'langItem': string;
  'langSwitherMenu': string;
  'list': string;
  'right': string;
  'shortcut': string;
  'statusBar': string;
  'worker': string;
}
declare var cssExports: CssExports;
export = cssExports;
