// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'botName': string;
  'button': string;
  'danger': string;
  'flag': string;
  'flagWrapper': string;
  'item': string;
  'langItem': string;
  'langSwitherMenu': string;
  'message': string;
  'statusBar': string;
}
declare var cssExports: CssExports;
export = cssExports;
