// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addBtn': string;
  'deleteImg': string;
  'errorIcon': string;
  'errorMessage': string;
  'fieldError': string;
  'fieldWrapper': string;
  'fieldWrapperHeader': string;
  'formSelect': string;
  'groupLabel': string;
  'hasError': string;
  'imgWrapper': string;
  'imgWrapperActions': string;
  'input': string;
  'label': string;
  'labelError': string;
  'labelWrapper': string;
  'textarea': string;
}
declare var cssExports: CssExports;
export = cssExports;
