// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addBtn': string;
  'borderTop': string;
  'deleteImg': string;
  'errorIcon': string;
  'fieldWrapperHeader': string;
  'groupLabel': string;
  'label': string;
  'labelWrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
