// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'flexContainer': string;
  'missingIcon': string;
}
declare var cssExports: CssExports;
export = cssExports;
