// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'spaced': string;
  'table': string;
  'tableRow': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
