// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'debug': string;
  'end': string;
  'entry': string;
  'level': string;
  'level-debug': string;
  'level-error': string;
  'level-info': string;
  'level-silly': string;
  'level-verbose': string;
  'level-warn': string;
  'logs': string;
  'message': string;
  'time': string;
}
export const cssExports: CssExports;
export default cssExports;
