import { type IntegrationDefinition, type BotDefinition } from '@botpress/sdk'
import { prepareCreateIntegrationBody } from '../api/integration-body'
import type commandDefinitions from '../command-definitions'
import * as errors from '../errors'
import { IntegrationLinter } from '../linter/integration-linter'
import { BotLinter } from '../linter/bot-linter'
import { getImplementationStatements } from '../sdk'
import { ProjectCommand } from './project-command'
import { prepareCreateBotBody } from '../api/bot-body'

export type LintCommandDefinition = typeof commandDefinitions.lint
export class LintCommand extends ProjectCommand<LintCommandDefinition> {
  public async run(): Promise<void> {
    const projectDef = await this.readProjectDefinitionFromFS()

    switch (projectDef.type) {
      case 'integration':
        return this._runLintForIntegration(projectDef.definition)
      case 'bot':
        return this._runLintForBot(projectDef.definition)
      case 'interface':
        throw new errors.BotpressCLIError('Interface linting is not yet implemented')
      default:
        throw new errors.BotpressCLIError('Unsupported project type')
    }
  }

  private async _runLintForBot(definition: BotDefinition): Promise<void> {
    const strippedDefinition = this._stripAutoGeneratedContentFromBot(definition)
    const parsedBotDefinition = await prepareCreateBotBody(strippedDefinition)
    const linter = new BotLinter(parsedBotDefinition)

    await linter.lint()
    linter.logResults(this.logger)

    if (linter.hasErrors()) {
      throw new errors.BotpressCLIError('Bot definition contains linting errors')
    }

    this.logger.success('Bot definition is valid')
  }

  private _stripAutoGeneratedContentFromBot(definition: BotDefinition) {
    return {
      ...definition,
      integrations: {},
    } as BotDefinition
  }

  private async _runLintForIntegration(definition: IntegrationDefinition): Promise<void> {
    const strippedDefinition = this._stripAutoGeneratedContentFromIntegration(definition)
    const parsedIntegrationDefinition = await prepareCreateIntegrationBody(strippedDefinition)
    const linter = new IntegrationLinter({ ...parsedIntegrationDefinition, secrets: strippedDefinition.secrets })

    await linter.lint()
    linter.logResults(this.logger)

    if (linter.hasErrors()) {
      throw new errors.BotpressCLIError('Integration definition contains linting errors')
    }

    this.logger.success('Integration definition is valid')
  }

  private _stripAutoGeneratedContentFromIntegration(definition: IntegrationDefinition) {
    const { actionNames, eventNames } = this._getAutoGeneratedContentOfIntegration(definition)

    return {
      ...definition,
      actions: Object.fromEntries(Object.entries(definition.actions ?? {}).filter(([key]) => !actionNames.has(key))),
      events: Object.fromEntries(Object.entries(definition.events ?? {}).filter(([key]) => !eventNames.has(key))),
    } as IntegrationDefinition
  }

  private _getAutoGeneratedContentOfIntegration(definition: IntegrationDefinition) {
    const actionNames = new Set<string>()
    const eventNames = new Set<string>()

    const interfacesStatements = getImplementationStatements(definition)
    for (const iface of Object.values(interfacesStatements)) {
      for (const actionDefinition of Object.values(iface.actions)) {
        actionNames.add(actionDefinition.name)
      }
      for (const eventDefinition of Object.values(iface.events)) {
        eventNames.add(eventDefinition.name)
      }
    }

    return { actionNames, eventNames } as const
  }
}
