// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'infoContent': string;
  'showMoreBtn': string;
}
declare var cssExports: CssExports;
export = cssExports;
