// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'active': string;
  'button': string;
  'content': string;
  'contentImgWrapper': string;
  'contentWrapper': string;
  'contentsWrapper': string;
  'contextMenuLabel': string;
  'error': string;
  'errorIcon': string;
  'execute': string;
  'failure': string;
  'hasJoinLabel': string;
  'headerWrapper': string;
  'highlighted': string;
  'img': string;
  'in': string;
  'joinLabel': string;
  'nodeWrapper': string;
  'out': string;
  'outRouting': string;
  'prompt': string;
  'promptPortContent': string;
  'router': string;
  'secondaryText': string;
  'success': string;
  'text': string;
  'textWrapper': string;
  'trigger': string;
}
declare var cssExports: CssExports;
export = cssExports;
