// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action-item': string;
  'condition': string;
  'defaultValue': string;
  'editableInput': string;
  'fn': string;
  'icon': string;
  'missingTranslation': string;
  'msg': string;
  'name': string;
}
declare var cssExports: CssExports;
export = cssExports;
