// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'fullsize': string;
  'leftSideBar': string;
  'mainContent': string;
  'yOverflowScroll': string;
}
declare var cssExports: CssExports;
export = cssExports;
