// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'customIcon': string;
  'logo': string;
  'sidebar': string;
  'small_tag': string;
  'tag': string;
  'tooltipContent': string;
}
export const cssExports: CssExports;
export default cssExports;
