// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions-container': string;
  'botReplies': string;
  'empty': string;
  'interaction': string;
  'interactionStatus': string;
  'reportInteractions': string;
  'scenario': string;
  'scenarioBody': string;
  'scenarioFooter': string;
  'scenarioHead': string;
  'scenarioPreview': string;
  'scenarioRecorder': string;
  'scenarioStatus': string;
  'subtitle': string;
  'summary': string;
  'title': string;
  'workspace': string;
}
declare var cssExports: CssExports;
export = cssExports;
