// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error': string;
  'expandBtn': string;
  'fieldWrapper': string;
  'formHeader': string;
  'formLabel': string;
  'formSelect': string;
  'hasError': string;
  'input': string;
  'noBorder': string;
  'noSelect': string;
  'textarea': string;
  'textareaWrapper': string;
  'typeField': string;
}
declare var cssExports: CssExports;
export = cssExports;
