// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fieldWrapper': string;
  'formSelect': string;
}
declare var cssExports: CssExports;
export = cssExports;
