// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'addBtn': string;
  'btn': string;
  'dropdown': string;
  'placeholder': string;
  'search': string;
  'select': string;
  'selectItem': string;
}
declare var cssExports: CssExports;
export = cssExports;
