// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'conversation': string;
  'date': string;
  'dateOuter': string;
  'header': string;
  'innerMessages': string;
  'messages': string;
  'pausedWarning': string;
  'toggle': string;
  'toggleDiv': string;
}
declare var cssExports: CssExports;
export = cssExports;
