// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'bot': string;
  'bpwChatBubble': string;
  'bpwChatBubbleContent': string;
  'composer': string;
  'composerContainer': string;
  'createdDate': string;
  'handoffAssigned': string;
  'message': string;
  'messageContainer': string;
  'messageList': string;
  'selected': string;
  'sendButton': string;
  'shortcutDropdown': string;
  'shortcutItem': string;
  'shortcutKey': string;
  'shortcutListItem': string;
  'shortcutValue': string;
  'user': string;
  'voiceButton': string;
}
declare var cssExports: CssExports;
export = cssExports;
