// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bot': string;
  'bpwChatBubble': string;
  'bpwChatBubbleContent': string;
  'createdDate': string;
  'handoffAssigned': string;
  'message': string;
  'messageContainer': string;
  'messageList': string;
  'user': string;
}
declare var cssExports: CssExports;
export = cssExports;
