// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'category': string;
  'name': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
