// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'invalid': string;
  'key': string;
  'keyTip': string;
  'mandatory': string;
  'table': string;
}
declare var cssExports: CssExports;
export = cssExports;
