// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionIcons': string;
  'actions': string;
  'addContentBtn': string;
  'bottomSection': string;
  'endBloc': string;
  'fieldWrapper': string;
  'formHeader': string;
  'formLabel': string;
  'formSelect': string;
  'item': string;
  'name': string;
  'node': string;
  'nodeBloc': string;
  'returnBloc': string;
  'returnToNodeSection': string;
  'section': string;
  'sidePanelForm': string;
  'subflowBloc': string;
  'textFields': string;
  'textInput': string;
  'textarea': string;
  'tip': string;
}
declare var cssExports: CssExports;
export = cssExports;
