// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appliedFilters': string;
  'chartMetric': string;
  'empty': string;
  'emptyState': string;
  'filtersButton': string;
  'filtersInputWrapper': string;
  'filtersShowing': string;
  'filtersWrapper': string;
  'header': string;
  'inputLabel': string;
  'mainWrapper': string;
  'metricName': string;
  'metricWrapper': string;
  'metricsContainer': string;
  'number': string;
  'numberMetric': string;
  'numberMetricValue': string;
  'pageTitle': string;
}
declare var cssExports: CssExports;
export = cssExports;
