@api = http://localhost:3200

### get info
# @name info
GET {{api}}/info


### do a training
# @name train
POST {{api}}/train
Content-Type: application/json

{
  "language": "en",
  "topics": [
    {
      "name": "global",
      "intents": [
        {
          "name": "fruit-is-moldy",
          "examples": [
            "fruit is moldy",
            "this fruit is moldy",
            "this [banana](fruit) is not good to eat",
            "theses [oranges](fruit) have passed",
            "theses [grapes](fruit) look bad",
            "theses [apples](fruit) look soo moldy"
          ],
          "variables": [
            {
              "name": "moldy_fruit",
              "types": ["fruits"]
            }
          ]
        },
        {
          "name": "hello",
          "variables": [],
          "examples": [
            "good day!",
            "good morning",
            "holla",
            "bonjour",
            "hey there",
            "hi bot",
            "hey bot",
            "hey robot",
            "hey!",
            "hi",
            "hello"
          ]
        },
        {
          "name": "talk-to-manager",
          "examples": [
            "talk to manager",
            "I want to talk to the manager",
            "Who's your boss?",
            "Can talk to the person in charge?",
            "I'd like to speak to your manager",
            "Can I talk to your boss? plz",
            "I wanna speak to manager please",
            "let me speak to your boss or someone"
          ],
          "variables": []
        },
        {
          "name": "where-is",
          "examples": [
            "where is [milk](thing_to_search) ?",
            "where are [apples](thing_to_search) ?",
            "can you help me find [apples](thing_to_search) ?",
            "I'm searching for [pie](thing_to_search) ?",
            "where is the [milk](thing_to_search) ?",
            "where are the [milk](thing_to_search) ?"
          ],
          "variables": [
            {
              "name": "thing_to_search",
              "types": ["fruits", "any"]
            }
          ]
        }
      ]
    }
  ],
  "enums": [
    {
      "name": "fruits",
      "fuzzy": 0.9,
      "values": [
        { "name": "banana", "synonyms": ["bananas"] },
        { "name": "apple", "synonyms": ["apples"] },
        { "name": "grape", "synonyms": ["grapes"] },
        { "name": "orange", "synonyms": ["oranges"] }
      ]
    }
  ],
  "password": "123456",
  "seed": 42
}
###
@modelId = {{train.response.body.modelId}}



### get training-status
# @name train-status
GET {{api}}/train/{{modelId}}?password=123456


### cancel training
# @name cancel-training
POST {{api}}/train/{{modelId}}/cancel
Content-Type: application/json

{
  "password": "123456"
}

### predict for sentence
# @name predict
POST {{api}}/predict/{{modelId}}
Content-Type: application/json

{
  "texts" : ["These grapes look moldy", "Can I talk with the person in charge?"],
  "password": "123456"
}