// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'clickable': string;
  'divider': string;
  'header': string;
  'item': string;
  'itemSpacing': string;
  'label': string;
  'list': string;
  'shortcut': string;
}
declare var cssExports: CssExports;
export = cssExports;
