// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'collapseBtn': string;
  'collapsibleContainer': string;
  'subSection': string;
}
declare var cssExports: CssExports;
export = cssExports;
