// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn_mini': string;
  'container': string;
  'empty': string;
  'header': string;
  'left': string;
  'list': string;
  'paging': string;
  'right': string;
  'search': string;
  'selected': string;
}
declare var cssExports: CssExports;
export = cssExports;
