// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block': string;
  'container': string;
  'container2': string;
  'header': string;
  'hovering': string;
  'inspector': string;
  'inspectorContainer': string;
}
declare var cssExports: CssExports;
export = cssExports;
