export const MODULE_NAME = 'hitlnext'
export const WEBSOCKET_TOPIC = 'hitlnext'
export const HANDOFF_TABLE_NAME = 'handoffs'
export const EVENT_TABLE_NAME = 'events'
export const COMMENT_TABLE_NAME = 'comments'
