export const MODULE_NAME = 'hitlnext'
export const WEBSOCKET_TOPIC = 'hitlnext'
export const HANDOFF_TABLE_NAME = 'handoffs'
export const EVENT_TABLE_NAME = 'events'
export const WEB_MESSAGE_TABLE_NAME = 'web_messages'
export const WEB_CONVERSATION_TABLE_NAME = 'web_conversations'
export const SRV_CHANNEL_USER_TABLE_NAME = 'srv_channel_users'
export const COMMENT_TABLE_NAME = 'comments'
