// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'button': string;
  'group': string;
  'label': string;
  'noMargin': string;
  'variables': string;
  'wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
