// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'emptyState': string;
  'grabbable': string;
  'mainoverlay': string;
  'modalFooter': string;
  'modalHeader': string;
  'overhidden': string;
  'section': string;
  'tabs': string;
  'title': string;
  'toolItem': string;
  'toolPanel': string;
  'treeNode': string;
}
declare var cssExports: CssExports;
export = cssExports;
