// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'checkboxContainer': string;
  'container': string;
  'create': string;
  'deleteEntity': string;
  'deleteIntent': string;
  'entity': string;
  'entityText': string;
  'filter': string;
  'flash': string;
  'headerTabs': string;
  'in': string;
  'list': string;
  'main': string;
  'navigationBar': string;
  'out': string;
  'sync': string;
  'synonym': string;
  'workspace': string;
}
declare var cssExports: CssExports;
export = cssExports;
