// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'header': string;
  'item': string;
  'label': string;
  'menu': string;
}
export const cssExports: CssExports;
export default cssExports;
