// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'deleteBtn': string;
  'dropdownWrapper': string;
  'separator': string;
}
declare var cssExports: CssExports;
export = cssExports;
