// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'h1': string;
  'h2': string;
  'h3': string;
  'h4': string;
  'h5': string;
  'h6': string;
}
declare var cssExports: CssExports;
export = cssExports;
