// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'amendForm': string;
  'chatPreview': string;
  'chatPreviewAvatar': string;
  'chatPreviewMessage': string;
  'chatPreviewMessage_Current': string;
  'chatPreviewMessage_Incoming': string;
  'chatPreviewMessage_Outgoing': string;
  'chatPreviewText': string;
  'contentFixed': string;
  'contentStretch': string;
  'newEventPreview': string;
  'padded': string;
  'sideList': string;
  'sideListItem': string;
  'sideListItemSelected': string;
  'sideListItemText': string;
  'sideListList': string;
  'sidePanel': string;
  'sidePanelContent': string;
  'sidePanelContentStretch': string;
}
declare var cssExports: CssExports;
export = cssExports;
