// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'applyAllButton': string;
  'contentFixed': string;
  'contentStretch': string;
  'mainView': string;
  'padded': string;
  'sideList': string;
  'sideListItem': string;
  'sideListItemSelected': string;
  'sideListItemText': string;
  'sideListList': string;
  'sidePanel': string;
  'sidePanelContent': string;
  'sidePanelContentStretch': string;
}
declare var cssExports: CssExports;
export = cssExports;
