// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'noPadding': string;
}
declare var cssExports: CssExports;
export = cssExports;
