// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'customTextarea': string;
  'error': string;
  'hasError': string;
  'items': string;
  'textareaWrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
