# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5dc1bbd9b4da1425005409a89e959df6"
name = "Admin Integration Staging"
application_url = "https://webhook.botpress.dev/oauth/wizard/start"
embedded = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://webhook.botpress.dev/oauth/wizard/oauth-callback" ]

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://controller.botpress.dev/v1/interation/shopify-admin"
