// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionModal': string;
  'formHeader': string;
  'wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
