// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fromAgent': string;
  'fromBot': string;
  'fromSystem': string;
  'fromUser': string;
  'icon': string;
  'message': string;
}
declare var cssExports: CssExports;
export = cssExports;
