// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dropdown': string;
  'empty': string;
  'icon': string;
  'invisible': string;
  'item': string;
  'item-unread': string;
  'level-error': string;
  'level-info': string;
  'level-success': string;
  'markAsReadButton': string;
  'message': string;
  'topMenu': string;
}
declare var cssExports: CssExports;
export = cssExports;
