// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contentAnswer': string;
  'customTextarea': string;
  'hasError': string;
  'items': string;
  'textarea': string;
  'textareaWrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
