// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionDialogContent': string;
  'actionSelectItem': string;
  'actionServer': string;
  'category': string;
  'description': string;
  'fieldError': string;
  'imgWrapper': string;
  'imgWrapperActions': string;
  'items': string;
  'multipleInputs': string;
  'wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
