// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'buttonTip': string;
  'centerContainer': string;
  'centerElement': string;
  'entityItem': string;
  'entityLabel': string;
  'entityNameInput': string;
  'link': string;
  'normalContainer': string;
  'selectionText': string;
  'shortcutLabel': string;
  'type': string;
}
declare var cssExports: CssExports;
export = cssExports;
