// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'failure': string;
  'sep': string;
  'success': string;
}
declare var cssExports: CssExports;
export = cssExports;
