// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'events': string;
  'level-debug': string;
  'level-error': string;
  'level-info': string;
  'level-silly': string;
  'level-verbose': string;
  'level-warn': string;
  'line': string;
  'logs-panel': string;
  'logs-panel-footer': string;
  'panel': string;
  'panel-checkbox': string;
  'time': string;
}
declare var cssExports: CssExports;
export = cssExports;
