// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ConfirmDialogContainer': string;
  'button': string;
  'confirmButton': string;
  'dialog': string;
  'icon': string;
}
declare var cssExports: CssExports;
export = cssExports;
