// This file is automatically generated.
// Please do not change this file!
interface CssExports {
<<<<<<< HEAD:src/bp/ui-shared/src/Form/FormFields/Switch/style.scss.d.ts
  'switch': string;
=======
  'item': string;
  'waitInput': string;
>>>>>>> master:src/bp/ui-studio/src/web/views/FlowBuilder/diagram/nodes/StandardContents/style.scss.d.ts
}
declare var cssExports: CssExports;
export = cssExports;
