// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'audioWrapper': string;
  'audioWrapperActions': string;
  'audioWrapperSource': string;
  'deleteFile': string;
  'fileWrapper': string;
  'fileWrapperActions': string;
  'fileWrapperFile': string;
  'imageWrapper': string;
  'imageWrapperActions': string;
  'videoWrapper': string;
  'videoWrapperActions': string;
  'videoWrapperSource': string;
}
declare var cssExports: CssExports;
export = cssExports;
