// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'menu': string;
  'menuButton': string;
  'popover': string;
  'toggle': string;
  'toggleActive': string;
}
declare var cssExports: CssExports;
export = cssExports;
