// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'active': string;
  'button': string;
  'content': string;
  'contentImgWrapper': string;
  'contentWrapper': string;
  'contentsWrapper': string;
  'danger': string;
  'debugInfo': string;
  'error': string;
  'errorIcon': string;
  'execute': string;
  'failure': string;
  'hasError': string;
  'hasJoinLabel': string;
  'headerWrapper': string;
  'hidden': string;
  'highlighted': string;
  'img': string;
  'in': string;
  'joinLabel': string;
  'large': string;
  'listen': string;
  'nodeWrapper': string;
  'out': string;
  'outRouting': string;
  'promptPortContent': string;
  'readOnly': string;
  'results': string;
  'router': string;
  'say_something': string;
  'secondaryText': string;
  'skill-call': string;
  'small': string;
  'smallButton': string;
  'standard': string;
  'sub-workflow': string;
  'success': string;
  'text': string;
  'textWrapper': string;
  'total': string;
  'trigger': string;
}
declare var cssExports: CssExports;
export = cssExports;
