// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'attribute': string;
  'attributes': string;
  'header': string;
  'label': string;
  'profile': string;
  'profilePic': string;
  'value': string;
}
declare var cssExports: CssExports;
export = cssExports;
