const TYPES = {
  Logger_Name: Symbol.for('Logger_Name'),
  Logger: Symbol.for('Logger'),
  Database: Symbol.for('Database'),
  ModuleLoader: Symbol.for('ModuleLoader'),
  Botpress: Symbol.for('Botpress'),
  HTTPServer: Symbol.for('HTTPServer'),
  ConfigProvider: Symbol.for('ConfigProvider'),
  BotRepository: Symbol.for('BotRepository'),
  ProjectLocation: Symbol.for('ProjectLocation'),
  GhostService: Symbol.for('GhostService'),
  IsProduction: Symbol.for('IsProduction'),
  MiddlewareService: Symbol.for('MiddlewareService'),
  CMSService: Symbol.for('CMSService'),
  InMemoryDatabase: Symbol.for('InMemoryDatabase'),
  FlowService: Symbol.for('FlowService'),
  BotLoader: Symbol.for('BotLoader'),
  StorageDriver: Symbol.for('StorageDriver'),
  ObjectCache: Symbol.for('ObjectCache'),
  ActionService: Symbol.for('ActionService'),
  IsPackaged: Symbol.for('IsPackaged'),
  Queue: Symbol.for('Queue'),
  HookService: Symbol.for('HookService'),
  EventEngine: Symbol.for('EventEngine'),
  DialogEngine: Symbol.for('DialogEngine'),
  SessionRepository: Symbol.for('StateManager'),
  SessionService: Symbol.for('SessionService')
}

export { TYPES }
