// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error': string;
  'flex': string;
  'spaced': string;
  'textArea': string;
}
declare var cssExports: CssExports;
export = cssExports;
