// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'expressionWrapper': string;
  'expressionWrapperActions': string;
  'fieldContainer': string;
  'fieldError': string;
  'flexContainer': string;
  'italic': string;
  'toggleLink': string;
}
declare var cssExports: CssExports;
export = cssExports;
