// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dialog': string;
  'editing': string;
  'formHeader': string;
  'inputParamWrapper': string;
  'last': string;
  'tip': string;
  'triggerConditionItemWrapper': string;
  'triggerConditionsWrapper': string;
  'triggerWrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
