// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bar': string;
  'barContainer': string;
  'canShowFull': string;
  'collapsibleContainer': string;
  'confidence': string;
  'container': string;
  'container2': string;
  'content': string;
  'debuggerIcon': string;
  'error': string;
  'expanded': string;
  'group': string;
  'header': string;
  'hovering': string;
  'infoBox': string;
  'inspector': string;
  'inspectorContainer': string;
  'itemButton': string;
  'notFound': string;
  'percentBar': string;
  'processingItem': string;
  'processingSection': string;
  'section': string;
  'sectionTitle': string;
  'splash': string;
  'stacktrace': string;
  'subSection': string;
  'switchViewBtn': string;
  'time': string;
  'triggerGroup': string;
  'triggersContainer': string;
  'truncate': string;
}
declare var cssExports: CssExports;
export = cssExports;
