// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block': string;
  'container2': string;
  'content': string;
  'header': string;
  'hovering': string;
  'inspector': string;
  'inspectorContainer': string;
  'notFound': string;
  'splash': string;
  'subSection': string;
  'summaryTable': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
