// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'section': string;
  'sectionTitle': string;
}
declare var cssExports: CssExports;
export = cssExports;
