// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'bot_name': string;
  'bot_views': string;
  'botbadge': string;
  'bottomRow': string;
  'compact_view': string;
  'create': string;
  'createbot_btn': string;
  'customIcon': string;
  'extraFilters': string;
  'filterCallout': string;
  'filterField': string;
  'filterWrapper': string;
  'link': string;
  'more': string;
  'pipeline_bot': string;
  'pipeline_edit_button': string;
  'pipeline_title': string;
  'pipeline_view': string;
  'reviewNeeded': string;
  'row': string;
  'spaced': string;
  'stage_approval_btns': string;
  'table': string;
  'tableRow': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
