name: 'Refresh Instagram Access Tokens'
description: 'Refreshes Instagram access token, updates the integrations secrets and update the token in 1Password'

inputs:
  environment:
    type: choice
    description: 'Environment to deploy the integration to'
    required: true
    options:
      - staging
      - production
  token_cloud_ops_account:
    description: 'Cloud Ops account token'
    required: true
  cloud_ops_workspace_id:
    description: 'Cloud Ops workspace id'
    required: true
  api_url:
    description: 'API URL'
    required: true
  current_token:
    description: 'Current token'
    required: true
  secret_name:
    description: 'Secret name'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Refresh Instagram Access Tokens
      id: refresh_tokens
      shell: bash
      env:
        BP_API_URL: ${{ inputs.api_url }}
        BP_WORKSPACE_ID: ${{ inputs.cloud_ops_workspace_id }}
        BP_TOKEN: ${{ inputs.token_cloud_ops_account }}
      with:
        CURRENT_TOKEN: ${{ inputs.current_token }}
      run: |
        refresh_result=$(pnpm -F 'instagram' exec -- pnpm run --silent refreshTokens --json --instagramRefreshToken "$CURRENT_TOKEN")
        new_token=$(echo "$refresh_result" | jq -r '.refreshedToken')
        if [ -z "$new_token" ]; then
          echo "❌ Error: Failed to refresh token" >&2
          exit 1
        fi

        echo "$refresh_result" | jq -r '.message'
        echo "✅ Tokens refreshed successfully"
        echo "$new_token" >> "$GITHUB_OUTPUT"
    - uses: ./.github/actions/create-or-update-secret
      with:
        secret_name: ${{ inputs.secret_name }}
        secret_value: ${{ steps.refresh_tokens.outputs.result }}
