name: 'Refresh Instagram Access Tokens'
description: 'Refreshes Instagram access token, updates the integrations secrets and update the token in 1Password'

inputs:
  environment:
    type: choice
    description: 'Environment to deploy the integration to'
    required: true
    options:
      - staging
      - production
  item_name:
    description: '1Password item name containing the Instagram access token'
    required: true
  field_name:
    description: '1Password field name containing the Instagram access token'
    required: true
  token_cloud_ops_account:
    description: 'Cloud Ops account token'
    required: true
  cloud_ops_workspace_id:
    description: 'Cloud Ops workspace id'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Refresh Instagram Access Tokens
      shell: bash
      env:
        BP_API_URL: ${{ inputs.environment == 'staging' && 'https://api.botpress.dev' || 'https://api.botpress.cloud' }}
        BP_WORKSPACE_ID: ${{ inputs.cloud_ops_workspace_id }}
        BP_TOKEN: ${{ inputs.token_cloud_ops_account }}
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      run: |
        script_path="./.github/scripts/refresh-instagram-access-tokens.sh"
        chmod +x $script_path
        $script_path "${{ inputs.item_name }}" "${{ inputs.field_name }}"
