// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'audioWrapper': string;
  'audioWrapperActions': string;
  'audioWrapperSource': string;
  'deleteFile': string;
  'imageWrapper': string;
  'imageWrapperActions': string;
}
declare var cssExports: CssExports;
export = cssExports;
