// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'emptyState': string;
  'isTopic': string;
  'tree': string;
  'treeItem': string;
}
declare var cssExports: CssExports;
export = cssExports;
