// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'addBtn': string;
  'contextMenu': string;
  'draggable': string;
  'ellipsisText': string;
  'emptyState': string;
  'importInput': string;
  'inlineEditing': string;
  'inputLabel': string;
  'isTopic': string;
  'larger': string;
  'largerSelected': string;
  'searchBar': string;
  'tag': string;
  'topicName': string;
  'tree': string;
  'treeItem': string;
}
declare var cssExports: CssExports;
export = cssExports;
