// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'placeholder': string;
  'spaced': string;
}
declare var cssExports: CssExports;
export = cssExports;
