source 'https://rubygems.org'
ruby '>= 2.1'

gem 'jekyll', '~> 3.8.3'
gem 'jekyll-redirect-from'
gem 'jekyll-paginate'
gem 'crowdin-cli'
gem 'kramdown'#, '~>1.11' # _plugins/jekyll_ext.rb messes with internals
gem 'rouge' #,  '<2' # rouge2 will require changes in _plugins/jekyll_ext.rb
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
gem 'jekyll-assets'
gem 'sprockets-es6'
gem 's3_website'
gem 'octokit'
group :jekyll_plugins do
  gem 'algoliasearch-jekyll', '~> 0.9.0'
end
