// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'baseNode': string;
  'content': string;
  'contentImgWrapper': string;
  'fullSize': string;
  'header': string;
  'highlightedNode': string;
  'img': string;
  'in': string;
  'item': string;
  'nodeAction': string;
  'nodeExecute': string;
  'nodeFailure': string;
  'nodeListen': string;
  'nodeRouter': string;
  'nodeSaySomething': string;
  'nodeSuccess': string;
  'nodeTrigger': string;
  'nodeTriggerConditions': string;
  'out': string;
  'outRouting': string;
  'ports': string;
  'primaryText': string;
  'secondaryText': string;
  'section-next': string;
  'textWrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
