// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'baseNode': string;
  'content': string;
  'header': string;
  'highlightedNode': string;
  'in': string;
  'item': string;
  'nodeExecute': string;
  'nodeListen': string;
  'nodeRouter': string;
  'nodeSaySomething': string;
  'out': string;
  'outRouting': string;
  'ports': string;
  'section-next': string;
  'srd-node--selected': string;
}
declare var cssExports: CssExports;
export = cssExports;
