// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'label-colors-1': string;
  'label-colors-10': string;
  'label-colors-11': string;
  'label-colors-12': string;
  'label-colors-2': string;
  'label-colors-3': string;
  'label-colors-4': string;
  'label-colors-5': string;
  'label-colors-6': string;
  'label-colors-7': string;
  'label-colors-8': string;
  'label-colors-9': string;
}
declare var cssExports: CssExports;
export = cssExports;
