// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'header': string;
  'markdown': string;
  'selectContext': string;
  'tools': string;
}
declare var cssExports: CssExports;
export = cssExports;
