// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contentButton': string;
  'elementListInput': string;
  'inputArea': string;
  'inputError': string;
  'listElement': string;
  'listElementIcon': string;
  'listElementValue': string;
  'textField': string;
}
declare var cssExports: CssExports;
export = cssExports;
