// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bp3-disabled': string;
  'workspaceButton': string;
}
export const cssExports: CssExports;
export default cssExports;
