// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'carousel': string;
  'content': string;
  'contentImgWrapper': string;
  'contentWrapper': string;
  'extraItems': string;
  'img': string;
  'textWrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
