// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'float': string;
  'tabs': string;
}
declare var cssExports: CssExports;
export = cssExports;
