// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'count': string;
  'disabled': string;
  'selected': string;
  'sidebar': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
