// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'link': string;
  'logo': string;
  'sidebar': string;
  'tag': string;
}
declare var cssExports: CssExports;
export = cssExports;
