/**
 * Generated types for this project
 * Auto-generated by `dab sync` - do not edit manually
 */

import type { ProjectContext } from '@botpress-private/dab'


/**
 * Available provisions for this project
 */
export type ProjectProvisions = {
  'iamRoles': {
  'sharedIamRoleArn': string
  'stagingIamRoleArn': string
  'productionIamRoleArn': string
}
}

/**
 * Available variables for this project
 */
export type ProjectVariables = {
  'DOMAIN': string
}

/**
 * Available secrets for this project
 */
export type ProjectSecrets = {
  [key: string]: never
}

/**
 * Typed context for this project with precise provision, variable, and secret keys
 */
export type SyncedProjectContext = Extract<ProjectContext, { type: 'web-app' }> & {
  provisions: ProjectProvisions
  variables: ProjectVariables
  secrets: ProjectSecrets
}
