// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'divide': string;
  'inspectorMenu': string;
  'item': string;
  'menu': string;
  'padded': string;
  'small': string;
  'tab': string;
  'tabContainer': string;
  'tabs': string;
  'verticalTab': string;
}
declare var cssExports: CssExports;
export = cssExports;
