// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badge': string;
  'btn--text': string;
  'container': string;
  'fingerprint': string;
  'icon': string;
  'info': string;
  'label': string;
  'licenceStatus': string;
  'license-infos__icon': string;
  'licenseStatusContainer': string;
  'licensed': string;
  'limits': string;
  'refresh': string;
  'status': string;
  'table': string;
  'unlicensed': string;
}
export const cssExports: CssExports;
export default cssExports;
