// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'btn-group': string;
  'container': string;
  'dates': string;
  'details': string;
  'emailField': string;
  'field': string;
  'filterCallout': string;
  'filterWrapper': string;
  'infoSquare': string;
  'list': string;
  'nameZone': string;
  'picture': string;
  'pullLeft': string;
  'role': string;
  'role_header': string;
  'spaced': string;
  'table': string;
  'tableRow': string;
  'title': string;
  'user': string;
}
export const cssExports: CssExports;
export default cssExports;
