// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottom': string;
  'left': string;
  'off': string;
  'on': string;
  'right': string;
  'tooltip': string;
  'tooltipArrow': string;
  'tooltipInner': string;
  'tooltipwrapper': string;
  'top': string;
}
declare var cssExports: CssExports;
export = cssExports;
