// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottom': string;
  'left': string;
  'right': string;
  'tooltip': string;
  'tooltipInner': string;
  'tooltipedElement': string;
  'top': string;
}
declare var cssExports: CssExports;
export = cssExports;
