// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'content_wrapper': string;
  'fullwidth': string;
  'overflow': string;
  'statusBar': string;
  'title': string;
  'unlicensed': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
