// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'contentsWrapper': string;
  'contextMenuLabel': string;
  'error': string;
  'errorIcon': string;
  'headerWrapper': string;
  'in': string;
  'nodeWrapper': string;
  'out': string;
  'outRouting': string;
}
declare var cssExports: CssExports;
export = cssExports;
