// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blockHeader': string;
  'contentsWrapper': string;
  'in': string;
  'nodeWrapper': string;
  'out': string;
  'outRouting': string;
  'selected': string;
}
declare var cssExports: CssExports;
export = cssExports;
