// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'loadingContainer': string;
  'size-large': string;
  'size-normal': string;
  'size-small': string;
}
declare var cssExports: CssExports;
export = cssExports;
