// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'allPaused': string;
  'current': string;
  'empty': string;
  'filter': string;
  'header': string;
  'sidebar': string;
  'toggle': string;
  'users': string;
}
declare var cssExports: CssExports;
export = cssExports;
