// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'NPSInput-slidein': string;
  'animated': string;
  'close': string;
  'inner': string;
  'message': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
