export { addCommentToDiscussion } from './add-comment-to-discussion'
export { addCommentToPage } from './add-comment-to-page'
export { addPageToDb } from './add-page-to-db'
export { getDb } from './get-db'
export { deleteBlock } from './delete-block'
