// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'agentBtn': string;
  'agentBtnText': string;
  'agentBtnWrapper': string;
  'agentItem': string;
  'agentList': string;
  'agentListItem': string;
  'app': string;
  'badge': string;
  'bot': string;
  'bpwChatBubble': string;
  'bpwChatBubbleContent': string;
  'clientName': string;
  'column': string;
  'commentForm': string;
  'conversationContainer': string;
  'coversationButton': string;
  'createdDate': string;
  'divider': string;
  'dot': string;
  'emptyContainer': string;
  'handoffItem': string;
  'handoffItemUrgent': string;
  'handoffList': string;
  'hitlToolBar': string;
  'info': string;
  'liveConversation': string;
  'mainContent': string;
  'mainNav': string;
  'message': string;
  'messageContainer': string;
  'messageList': string;
  'profileHeader': string;
  'sidebar': string;
  'sidebarContainer': string;
  'table': string;
  'unreadDot': string;
  'user': string;
  'w100': string;
  'webchatIframe': string;
  'webchatWrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
