name: Check Shell Scripts

on:
  pull_request:
    paths:
      - '**/*.sh'
      - .github/workflows
      - .github/actions

jobs:
  check-shells:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check shell scripts
        uses: botpress/gh-actions/check-shells@v3
