name: Check Integration Categories

on: pull_request

permissions:
  id-token: write
  contents: read

jobs:
  check-integration-categories:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: 'integrations/**/*.{ts,md,svg,vrl}'
          separator: '\n'
      - name: Check integration categories
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          modified_integrations=$(echo -e "$CHANGED_FILES" | awk -F'/' '{print $2}' | sort -u)

          should_fail=0

          for integration in $modified_integrations; do
            if [ ! -d "integrations/$integration" ]; then
              continue
            fi

            echo "Checking $integration"

            if ! ./.github/scripts/integration-has-valid-category.sh "$integration"; then
              should_fail=1
            fi
          done

          if [ "$should_fail" -ne 0 ]; then
            echo "Please add a valid category attribute to your integration definition before pushing your changes."
            exit 1
          fi
