name: Deploy Chat Production

on:
  workflow_dispatch:
    inputs:
      branchOrCommit:
        description: 'Branch/Commit/Tag to deploy'
        required: false
        type: string
        default: 'master'
      skipDeploy:
        description: 'Skip deployment to ECS'
        required: false
        type: boolean
        default: false
      builder:
        description: 'Image Builder'
        required: false
        type: choice
        options:
          - docker
          - depot
        default: 'depot'

permissions:
  id-token: write
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  deploy-chat-production:
    runs-on: ubuntu-latest
    steps:
      - uses: botpress/gh-actions/full-service-deploy@v3.3
        with:
          service: chat
          repository: chat-integration
          dockerfile: integrations/chat/Dockerfile
          context: .
          builder: ${{ inputs.builder || 'depot' }}
          role-ecs-update: skynet_infra_update
          skip-ecs-update: ${{ inputs.skipDeploy }}
          create-tag: true
          ref: ${{ inputs.branchOrCommit || github.sha }}
          environment: production
