name: Deploy Telegram Integration Staging

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required for OIDC
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          registry-url: https://npm.pkg.github.com
          scope: '@botpress-private'
      - run: pnpm install --frozen-lockfile
        working-directory: .ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PRIVATE_NPM_TOKEN }}
      - uses: botpress/dab/setup@action-v1
        with:
          environment: staging
          infisical-client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
          infisical-client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          config-file: ./.ci/telegram.ts
      - run: pnpm exec dab deploy --env=staging --file=telegram.ts
        working-directory: .ci
