name: Deploy Chat Production

on:
  workflow_dispatch:
    inputs:
      branchOrCommit:
        description: 'Branch/Commit/Tag to deploy'
        required: false
        type: string
        default: 'master'
      skipDeploy:
        description: 'Skip deployment to ECS'
        required: false
        type: boolean
        default: false
      builder:
        description: 'Image Builder'
        required: false
        type: choice
        options:
          - docker
          - depot
        default: 'depot'

permissions:
  id-token: write
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  deploy-chat-production:
    runs-on: ubuntu-latest
    steps:
      - uses: botpress/gh-actions/full-service-deploy@v3.3
        with:
          service: chat
          repository: chat-integration
          dockerfile: integrations/chat/Dockerfile
          context: .
          builder: ${{ inputs.builder || 'depot' }}
          role-ecs-update: botpress_infra_update
          skip-ecs-update: ${{ inputs.skipDeploy }}
          create-tag: true
          ref: ${{ inputs.branchOrCommit || github.sha }}
          environment: production

  update-integration-url:
    needs: deploy-chat-production
    if: ${{ !inputs.skipDeploy }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branchOrCommit || github.sha }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Deploy integration with ECS URL
        run: |
          pnpm bp login -y \
            --api-url "https://api.botpress.cloud" \
            --workspaceId "${{ secrets.PRODUCTION_CLOUD_OPS_WORKSPACE_ID }}" \
            --token "${{ secrets.PRODUCTION_TOKEN_CLOUD_OPS_ACCOUNT }}"

          pnpm -F @botpresshub/chat -c exec -- \
            bp deploy -v -y --noBuild --visibility public --allowDeprecated \
            --url "http://chat.private:9271"

  ping-success:
    needs: [deploy-chat-production, update-integration-url]
    runs-on: ubuntu-latest
    steps:
      - run: curl -m 10 --retry 5 ${{ secrets.CHAT_DEPLOY_PRODUCTION_PING_URL }}

  ping-failure:
    needs: [deploy-chat-production, update-integration-url]
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - run: curl -m 10 --retry 5 ${{ secrets.CHAT_DEPLOY_PRODUCTION_PING_URL }}/fail
