// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'btn': string;
  'editor': string;
  'editorContainer': string;
  'floatingButtons': string;
  'hidden': string;
  'padding': string;
  'sidePanel': string;
  'status': string;
  'tab': string;
  'tabsContainer': string;
  'warning': string;
}
declare var cssExports: CssExports;
export = cssExports;
