// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'btn': string;
  'editor': string;
  'editorContainer': string;
  'section': string;
  'sidePanel': string;
  'splashScreen': string;
  'status': string;
  'tab': string;
  'tabsContainer': string;
}
declare var cssExports: CssExports;
export = cssExports;
