// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'diagram': string;
  'diagramLegacy': string;
}
declare var cssExports: CssExports;
export = cssExports;
