// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'codeEditor': string;
  'diagram': string;
  'emulator-open': string;
  'header': string;
  'hidden': string;
  'title': string;
  'wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
