// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'separator': string;
  'toolbar': string;
  'unsavedText': string;
  'wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
