// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action_button': string;
  'action_disabled': string;
  'container': string;
  'infoTooltip': string;
  'sidebar': string;
  'sidebar_hidden': string;
  'sidebar_section': string;
  'splashScreen': string;
}
declare var cssExports: CssExports;
export = cssExports;
